In [1]:
import numpy as np
import pandas as pd

In [4]:
data = {
    'Name ' : [ 'John' , 'Anna' , 'Peter' , 'Tom'],
    'Age '  : [ 20 , 30 , 19 , 21 ],
    'City'  : ['Paris' , 'London' , 'Mumbai' , 'Sydney'],
    'Salary': [20000 , 10000 , 23000 , 13000]
}
df = pd.DataFrame(data)
df

   Name   Age     City  Salary
0   John    20   Paris   20000
1   Anna    30  London   10000
2  Peter    19  Mumbai   23000
3    Tom    21  Sydney   13000

In [11]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
columns = ["Name" , "Age" , "City" , "Salary"] 
df2 = pd.DataFrame(data_list,columns = columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [12]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [13]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [14]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [16]:
df2[ "Designation" ] = ["HR" , "CEO" , "Manager" , "HR"]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000          HR
1   Anna   34     Paris   70000         CEO
2  Peter   29    Berlin   62000     Manager
3  Linda   42    London   85000          HR

In [25]:
df2[ "Designation" ] = ["HR" , "CEO" , "Manager" , "HR"]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000          HR
1   Anna   34     Paris   70000         CEO
2  Peter   29    Berlin   62000     Manager
3  Linda   42    London   85000          HR

In [26]:
df2.drop("Designation" , axis = 1, inplace = True)

In [27]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [29]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [30]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [32]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [33]:
df2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [34]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [35]:
df2.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [36]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [39]:
#Age grater than 20
df2[df2["Age"]> 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [45]:
#Age greater than 30 and city = PARIS
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000